#!/bin/bash

# Make sure you're in correct place
cd ~/xero_dev/ContactsAutoCompleter

# Reset link in bower
bower unlink contacts-autocompleter
bower clean cache
bower link contacts-autocompleter

# Rebuild ContactsAutoCompleter
npm install

# Start ContactsAutoCompleter watch
npm run watch

