#!/bin/bash

# Setup ContactsAutoCompleter Session
SESSION='cac'
tmux -2 new-session -d -s $SESSION

# Setup XeroWeb window
cd ~/xero_dev/Xero/project/XeroWeb/
tmux rename-window -t $SESSION:1 XeroWeb
cd ~/xero_dev/Xero/
tmux split-window -v -p 25
tmux select-pane -t 1

# Setup ContactsAutoCompleter
cd ~/xero_dev/ContactsAutoCompleter/
tmux new-window -t $SESSION -n ContactsAutoCompleter
tmux split-window -v -p 25
tmux select-pane -t 2
tmux split-window -h -p 50
tmux select-pane -t 1

# Setup contact-autcompleter window
cd ~/xero_dev/contacts-autocompleter/
tmux new-window -t $SESSION -n contacts-autocomplter
tmux split-window -v -p 25
tmux select-pane -t 1

# Select main window
tmux select-window -t 1
