#
# ZSH Configuration
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Setup NVM for Node version management
export NVM_DIR="/Users/mgreen/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Aliases
# --------------------------
# Python: virtualenv aliases
alias virtualenv3='virtualenv -p /usr/local/bin/python3.5 venv'
alias activate='source venv/bin/activate'

# Axial: www release 
alias release_www="ssh mgreen@web1.axialmarket.com 'cd /var/www; sudo git pull origin master'"

# Tmux: use system subl command
alias subl='reattach-to-user-namespace subl'
alias ta='tmux attach -t'
